; =================================================================================================
; SHOWCASE: DIFFERENT COLLIDERS
; =================================================================================================

[Mesh:Prc_Floor]
Type = procedural
Shape = Box
Width = 20.0
Height = 1.0
Depth = 20.0

[Shader:Shdr_Phong]
Type = Lit
VS_Path = defaults/Phong_Forward_vert.spv
PS_Path = defaults/Phong_Forward_frag.spv

[Texture:Tex_Checker]
Type = 2D
Path = demo-scenes/checkerboard.png

[Material:Mat_Floor]
Shader = Shdr_Phong
Color = 0.5 0.5 0.5 1.0
Albedo = Tex_Checker

[Entity]
[Tag]
Name = MainCamera
[Transform]
Position = 0.0 5.0 -20.0
[Camera]
IsActive = true

[Entity]
[Tag]
Name = Sun
[Transform]
Position = 50.0 100.0 50.0
[DirectionalLight]

[Entity]
[Tag]
Name = Floor
[Transform]
Position = 0.0 -10.0 0.0
Scale = 20.0 1.0 20.0
[MeshRenderer]
Mesh = Prc_Floor
Material = Mat_Floor
[StaticEntity]
[BoxCollider]
LocalHalfExtents = 10.0 0.5 10.0
[AABB]

[Entity]
[Tag]
Name = BoxSpawner
[Transform]
Position = -4.0 15.0 0.0
[Spawner]
Shape = Box
StartTime = 0.5
RepeatingInterval = 0.01
RepeatingMaxCount = 1500
LocationType = RandomBox
LocationBoxMin = -50 5 -50
LocationBoxMax = 50 50 50
SizeRangeCuboid = 0.25 0.25 0.25 1.0 1.0 1.0
VelocityLinear = -2.0 0.0 -2.0 2.0 0.0 2.0
VelocityAngular = -3.14 -3.14 -3.14 3.14 3.14 3.14
Density = 1.0
PhysicsMaterialID = 0
IsGravityOn = true

[Entity]
[Tag]
Name = SphereSpawner
[Transform]
Position = -1.5 15.0 0.0
[Spawner]
Shape = Sphere
StartTime = 1.0
RepeatingInterval = 0.01
RepeatingMaxCount = 1500
LocationType = RandomBox
LocationBoxMin = -50 5 -50
LocationBoxMax = 50 50 50
SizeRangeSphere = 0.25 1.0
VelocityLinear = -2.0 0.0 -2.0 2.0 0.0 2.0
VelocityAngular = -3.14 -3.14 -3.14 3.14 3.14 3.14
Density = 1.0
PhysicsMaterialID = 0
IsGravityOn = true

[Entity]
[Tag]
Name = CapsuleSpawner
[Transform]
Position = 1.5 15.0 0.0
[Spawner]
Shape = Capsule
StartTime = 1.5
RepeatingInterval = 0.01
RepeatingMaxCount = 1500
LocationType = RandomBox
LocationBoxMin = -50 5 -50
LocationBoxMax = 50 50 50
SizeRangeCapsuleAndCylinderRadius = 0.25 0.5
SizeRangeCapsuleAndCylinderHeight = 0.5 2.0
VelocityLinear = -2.0 0.0 -2.0 2.0 0.0 2.0
VelocityAngular = -3.14 -3.14 -3.14 3.14 3.14 3.14
Density = 1.0
PhysicsMaterialID = 0
IsGravityOn = true

[Entity]
[Tag]
Name = CylinderSpawner
[Transform]
Position = 4.0 15.0 0.0
[Spawner]
Shape = Cylinder
StartTime = 2.0
RepeatingInterval = 0.01
RepeatingMaxCount = 1500
LocationType = RandomBox
LocationBoxMin = -50 5 -50
LocationBoxMax = 50 50 50
SizeRangeCapsuleAndCylinderRadius = 0.25 0.5
SizeRangeCapsuleAndCylinderHeight = 0.5 2.0
VelocityLinear = -2.0 0.0 -2.0 2.0 0.0 2.0
VelocityAngular = -3.14 -3.14 -3.14 3.14 3.14 3.14
Density = 1.0
PhysicsMaterialID = 0
IsGravityOn = true
