; =================================================================================================
; SHOWCASE: ANCHORED BUNGEE
; =================================================================================================

[Mesh:Prc_Sphere]
Type = procedural
Shape = Sphere
Radius = 1.0

[Mesh:Prc_Box]
Type = procedural
Shape = Box

[Shader:Shdr_Phong]
Type = Lit
VS_Path = defaults/Phong_Forward_vert.spv
PS_Path = defaults/Phong_Forward_frag.spv

[Material:Mat_Anchor]
Shader = Shdr_Phong
Color = 0.2 0.8 0.2 1.0

[Material:Mat_Blue]
Shader = Shdr_Phong
Color = 0.2 0.4 1.0 1.0

[Entity]
[Tag]
Name = MainCamera
[Transform]
Position = 0.0 10.0 -25.0
[Camera]
IsActive = true

[Entity]
[Tag]
Name = Sun
[Transform]
Position = 50.0 100.0 50.0
[DirectionalLight]

[Entity]
[Tag]
Name = AnchorPoint
[Transform]
Position = 0.0 20.0 0.0
Scale = 0.5 0.5 0.5
[MeshRenderer]
Mesh = Prc_Box
Material = Mat_Anchor
[RigidBody]
Mass = 0.0
CanSleep = false

[Entity]
[Tag]
Name = BungeeObject
[Transform]
Position = 0.0 19.0 0.0
[MeshRenderer]
Mesh = Prc_Sphere
Material = Mat_Blue
[RigidBody]
Mass = 2.0
CanSleep = false
[BodyAnchoredBungee]
OtherRigidBody = AnchorPoint
SpringConstant = 30.0
RestLength = 6.0