; =================================================================================================
; SHOWCASE: BODY SPRING (CHAIN REACTION)
; =================================================================================================

[Mesh:Prc_Sphere]
Type = procedural
Shape = Sphere
Radius = 1.0

[Mesh:Prc_Box]
Type = procedural
Shape = Box

[Shader:Shdr_Phong]
Type = Lit
VS_Path = defaults/Phong_Forward_vert.spv
PS_Path = defaults/Phong_Forward_frag.spv

[Material:Mat_Anchor]
Shader = Shdr_Phong
Color = 0.2 0.8 0.2 1.0

[Material:Mat_Red]
Shader = Shdr_Phong
Color = 1.0 0.2 0.2 1.0

[Material:Mat_Blue]
Shader = Shdr_Phong
Color = 0.2 0.4 1.0 1.0

[Entity]
[Tag]
Name = MainCamera
[Transform]
Position = 0.0 15.0 -35.0
[Camera]
IsActive = true

[Entity]
[Tag]
Name = Sun
[Transform]
Position = 50.0 100.0 50.0
[DirectionalLight]

[Entity]
[Tag]
Name = AnchorPoint
[Transform]
Position = 0.0 25.0 0.0
Scale = 0.5 0.5 0.5
[MeshRenderer]
Mesh = Prc_Box
Material = Mat_Anchor
[RigidBody]
Mass = 0.0
CanSleep = false

[Entity]
[Tag]
Name = MiddleBody
[Transform]
Position = 3.0 20.0 0.0
[MeshRenderer]
Mesh = Prc_Sphere
Material = Mat_Red
[RigidBody]
Mass = 2.0
CanSleep = false
[BodyAnchoredSpring]
AnchoredRigidBody = AnchorPoint
SpringConstant = 50.0
RestLength = 5.0

[Entity]
[Tag]
Name = BottomBody
[Transform]
Position = 6.0 15.0 0.0
[MeshRenderer]
Mesh = Prc_Sphere
Material = Mat_Blue
[RigidBody]
Mass = 2.0
CanSleep = false
[BodySpring]
OtherRigidBody = MiddleBody
SpringConstant = 50.0
RestLength = 5.0
ConnectionPoint = 0.0 0.5 0.0
OtherConnectionPoint = 0.0 -0.5 0.0