; =================================================================================================
; SHOWCASE: BUOYANCY
; =================================================================================================

[Mesh:Prc_Sphere]
Type = procedural
Shape = Sphere
Radius = 1.0

[Mesh:Prc_Box]
Type = procedural
Shape = Box

[Shader:Shdr_Phong]
Type = Lit
VS_Path = defaults/Phong_Forward_vert.spv
PS_Path = defaults/Phong_Forward_frag.spv

[Material:Mat_Red]
Shader = Shdr_Phong
Color = 1.0 0.2 0.2 1.0
Roughness = 0.5

[Material:Mat_Water]
Shader = Shdr_Phong
Color = 0.1 0.4 0.8 0.5
Roughness = 0.1

[Entity]
[Tag]
Name = MainCamera
[Transform]
Position = 0.0 5.0 -15.0
Rotation = 10.0 0.0 0.0
[Camera]
IsActive = true

[Entity]
[Tag]
Name = Sun
[Transform]
Position = 50.0 100.0 50.0
[DirectionalLight]
Color = 1.0 0.95 0.9 1.0

[Entity]
[Tag]
Name = WaterSurface_VisualOnly
[Transform]
Position = 0.0 0.0 0.0
Scale = 20.0 0.1 20.0
[MeshRenderer]
Mesh = Prc_Box
Material = Mat_Water
ForceTransparent = true

[Entity]
[Tag]
Name = FloatingSphere
[Transform]
Position = 0.0 10.0 0.0
[MeshRenderer]
Mesh = Prc_Sphere
Material = Mat_Red
[RigidBody]
Mass = 5.0
CanSleep = false
[AABB]
ShapeType = Sphere
ColliderType = Solid
[SphereCollider]
LocalRadius = 1.0
[BodyBuoyancy]
MaxDepth = 1.0
Volume = 4.18
WaterHeight = 0.0
LiquidDensity = 1000.0
CentreOfBuoyancy = 0.5 0.5 0.0
[BodyDrag]
K1 = 2.0
K2 = 0.5